spring:
  main:
    banner-mode: 'off'
  output:
    ansi:
      enabled: ALWAYS
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:h2:mem:testdb
logging.level:
  org.hibernate:
    type.descriptor.sql.BasicBinder : TRACE
app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpirationMsec: 864000000
    oauth2:
      authorizedRedirectUris:
        - http://localhost:3000/oauth2/redirect
